spring.application.name=pedido-mscv
server.port=8083

# ==========================================
# Base de Datos H2 (En Memoria para el Examen)
# ==========================================
spring.datasource.url=jdbc:h2:mem:pedidosdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Hibernate / JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ==========================================
# Configuración para AWS SQS (Real)
# ==========================================
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}
# URL real de la cola en AWS SQS
AWS_SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/546582930698/delishgo-pedidos-queue

# Optimización para AWS Lambda
spring.main.lazy-initialization=true

#lsdjfl