spring.application.name=restaurante-mscv
server.port=8085

# Base de datos H2
spring.datasource.url=jdbc:h2:file:./data/restaurants
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.hibernate.ddl-auto=create

# Consola de administración de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# Configuración para AWS SQS (Real)
# ==========================================
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}
# ⚠️ ¡IMPORTANTE! Reemplaza esto con la URL real de la cola que creaste en AWS SQS
AWS_SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/546582930698/delishgo-pedidos-queue
# Esto ya no lo necesitas porque ahora sí queremos que se conecte
# spring.cloud.aws.sqs.listener.auto-startup=false

# Optimización para AWS Lambda
spring.main.lazy-initialization=true