- name: Desplegar en el Servidor Remoto
        uses: appleboy/ssh-action@master  # O la acción de SSH que estés usando
        with:
          host: ${{ secrets.INPUT_HOST }}
          username: ${{ secrets.INPUT_USERNAME }}
          key: ${{ secrets.INPUT_KEY }}
          port: ${{ secrets.INPUT_PORT }}
          script: |
            set -e
            DEPLOY_DIR="/home/${{ secrets.INPUT_USERNAME }}/delishgo"
            cd "${DEPLOY_DIR}"

            # 1. Borramos la carpeta falsa generada por Docker para abrir paso al archivo real
            rm -rf nginx.conf

            # 2. Tu validación habitual de que el compose esté ahí
            test -f docker-compose.prod.yml

            # 3. Exportar variables de entorno de las imágenes
            export CLIENTE_IMAGE="${{ secrets.ECR_REGISTRY }}/delishgo-cliente-mscv:latest"
            export PEDIDO_IMAGE="${{ secrets.ECR_REGISTRY }}/delishgo-pedido-mscv:latest"
            export PRODUCTO_IMAGE="${{ secrets.ECR_REGISTRY }}/delishgo-producto-mscv:latest"
            export RESTAURANTE_IMAGE="${{ secrets.ECR_REGISTRY }}/delishgo-restaurante-mscv:latest"
            export FRONTEND_IMAGE="${{ secrets.ECR_REGISTRY }}/delishgo-frontend:latest"
            export CORS_ALLOWED_ORIGINS="${{ secrets.CORS_ALLOWED_ORIGINS }}"

            # 4. Instalación/Verificación de Docker Compose
            if ! docker compose version > /dev/null 2>&1; then
              echo "Instalando Docker Compose CLI Plugin manualmente..."
              mkdir -p ~/.docker/cli-plugins/
              curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
              chmod +x ~/.docker/cli-plugins/docker-compose
              docker compose version
            fi

            # 5. Login en AWS ECR y Despliegue
            aws ecr get-login-password --region "${{ secrets.AWS_REGION }}" | docker login --username AWS --password-stdin "${{ secrets.ECR_REGISTRY }}"

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
